### ISSUE TITLE
Failed to load cookies from /cookie.pickle: Invalid attribute 'partitioned'

### ISSUE THREAD

**Issue by jasonmadigan** [roondar/alexa2ha#3]
```
2024-09-17 18:07:48 - __main__ - ERROR - Failed to load cookies from /cookie.pickle: Invalid attribute 'partitioned'
2024-09-17 18:07:48 - __main__ - ERROR - Unhandled exception occurred
Traceback (most recent call last):
  File "/usr/src/app/./main.py", line 147, in main
    response = make_authenticated_request(list_items_url, cookie_file_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/./main.py", line 98, in make_authenticated_request
    raise ValueError("No cookies loaded")
ValueError: No cookies loaded
```

Using latest alexa_media_player

**Comment by jasonmadigan** [comment]
Likely related to pickle + python version:

https://github.com/python/cpython/pull/112714

Am running with 3.12.6
